repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: "v4.13.7"
    hooks:
      - id: commitizen
        stages: [commit-msg]
      - id: commitizen-branch
        stages: [pre-push]
        args:
          - --rev-range
          - origin/main..HEAD

  - repo: https://github.com/python-poetry/poetry
    rev: "2.3.2"
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-install

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: no-commit-to-branch
        args: ["--branch", "main"]
      - id: check-yaml
        args: ["--unsafe"]
        exclude: ^charts/financial-sigint/templates/
      - id: check-toml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys]
      - id: check-ast
      - id: debug-statements
      - id: check-docstring-first

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --check .
        language: system
        pass_filenames: false
      - id: ruff
        name: ruff
        entry: poetry run ruff check .
        language: system
        pass_filenames: false
      - id: flake8
        name: flake8
        entry: poetry run pflake8 .
        language: system
        pass_filenames: false
