{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "financial-sigint.fullname" . }}-secrets
  labels:
    {{- include "financial-sigint.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "financial-sigint.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecret.keys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Release.Name }}/{{ . }}
    {{- end }}
{{- end }}
