name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1" # Every Monday at 00:00 UTC

jobs:
  bump-release:
    name: Bump Release
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Bump Release
        id: release
        uses: python-semantic-release/python-semantic-release@39dd2052f2ce8282a5d932c31d58a2ca06d2550e # v10.6.1
        with:
          commit: true
          push: false
          vcs_release: false
          changelog: true
          git_committer_name: "github-actions[bot]"
          git_committer_email: "github-actions[bot]@users.noreply.github.com"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          verbosity: "2"

      - name: Push Release Commit to the Tag
        if: steps.release.outputs.released == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout "${{ steps.release.outputs.tag }}"
          git push origin HEAD:"refs/tags/${{ steps.release.outputs.tag }}" --force

      - name: Create Release
        if: steps.release.outputs.released == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.release.outputs.tag }}" \
            --title "${{ steps.release.outputs.tag }}" \
            --generate-notes \
            --prerelease
